begin;
create extension if not exists pgtap with schema extensions;
set local search_path=public,extensions;
select no_plan();
select has_function('public','server_redeem_paid_ticket',array['uuid','uuid','bytea'],'atomic redemption exists');
select ok(not has_function_privilege('anon','public.server_redeem_paid_ticket(uuid,uuid,bytea)','EXECUTE'),'anon cannot redeem');
select ok(not has_function_privilege('authenticated','public.server_redeem_paid_ticket(uuid,uuid,bytea)','EXECUTE'),'authenticated cannot invoke privileged RPC');
select ok(has_function_privilege('service_role','public.server_redeem_paid_ticket(uuid,uuid,bytea)','EXECUTE'),'service role can redeem');
select is((select proconfig::text from pg_proc where oid='public.server_redeem_paid_ticket(uuid,uuid,bytea)'::regprocedure),'{"search_path=\"\""}','empty search path');
select ok(not exists(select 1 from pg_proc p,lateral aclexplode(p.proacl) a where p.oid='public.server_redeem_paid_ticket(uuid,uuid,bytea)'::regprocedure and a.grantee=0 and a.privilege_type='EXECUTE'),'no PUBLIC execute');
set local role anon;
select throws_ok($$select * from public.server_redeem_paid_ticket(null,null,null)$$,'42501',null,'anon direct execution denied');
reset role;
set local role authenticated;
select throws_ok($$select * from public.server_redeem_paid_ticket(null,null,null)$$,'42501',null,'authenticated direct execution denied');
reset role;
\ir helpers/core_ticket_truth_lite_setup.inc
select pg_temp.record_and_fulfill('redeemclean','redeemclean',id,session_id) from fulfillment_orders where kind='clean';
reset role;
create temporary table scan_ticket as select * from public.tickets order by order_item_id,unit_sequence limit 1;
grant select on scan_ticket to service_role;
create function pg_temp.scan(p_owner uuid default 'a6100000-0000-4000-8000-000000000001',p_event uuid default 'a6200000-0000-4000-8000-000000000001') returns text language sql as $$
 select outcome from public.server_redeem_paid_ticket(p_owner,p_event,(select credential_hash from scan_ticket));
$$;
-- Probe deliberately contradictory historical state; every probe rolls back its changes.
create function pg_temp.scan_probe(p_sql text) returns text language plpgsql as $$
declare v_outcome text;
begin
 set local session_replication_role=replica;
 execute p_sql;
 set local session_replication_role=origin;
 select pg_temp.scan() into v_outcome;
 raise exception using errcode='PT001';
exception when sqlstate 'PT001' then return v_outcome;
end;
$$;
set local role service_role;
select throws_ok($$select pg_temp.scan('a6100000-0000-4000-8000-000000000002')$$,'42501','Admission forbidden','non-owner denied');
select throws_ok($$select * from public.server_redeem_paid_ticket('a6100000-0000-4000-8000-000000000002','a6200000-0000-4000-8000-000000000001',null)$$,'42501','Admission forbidden','ownership checked even before malformed hash');
select throws_ok($$select pg_temp.scan(null)$$,'42501','Admission forbidden','null owner denied');
select throws_ok($$select pg_temp.scan('a6100000-0000-4000-8000-000000000001','a6200000-0000-4000-8000-000000000009')$$,'42501','Admission forbidden','missing event denied');
select is(pg_temp.scan('a6100000-0000-4000-8000-000000000002','a6200000-0000-4000-8000-000000000002'),'wrong_event','coherent credential for another event');
select results_eq($$select * from public.server_redeem_paid_ticket('a6100000-0000-4000-8000-000000000002','a6200000-0000-4000-8000-000000000002',(select credential_hash from scan_ticket))$$,$$select 'wrong_event'::text,null::text$$,'wrong event reveals no foreign label');
select is((select outcome from public.server_redeem_paid_ticket('a6100000-0000-4000-8000-000000000001','a6200000-0000-4000-8000-000000000001',decode(repeat('f',64),'hex'))),'invalid','unknown hash invalid');
select is((select outcome from public.server_redeem_paid_ticket('a6100000-0000-4000-8000-000000000001','a6200000-0000-4000-8000-000000000001','\x00')),'invalid','short hash invalid');
reset role;
select is(pg_temp.scan_probe($$delete from public.tickets where id=(select id from scan_ticket)$$),'invalid','missing credential invalid');
select is(pg_temp.scan_probe($$delete from public.tickets where id<>(select id from scan_ticket)$$),'invalid','incomplete purchased set cannot admit remaining ticket');
select is(pg_temp.scan_probe($$update public.tickets set unit_sequence=4 where id=(select id from scan_ticket)$$),'invalid','source sequence contradiction');
select is(pg_temp.scan_probe($$update public.tickets set admission_label='Wrong' where id=(select id from scan_ticket)$$),'invalid','source label contradiction');
select is(pg_temp.scan_probe($$update public.tickets set organizer_id='a6100000-0000-4000-8000-000000000002' where id=(select id from scan_ticket)$$),'invalid','organizer contradiction');
select is(pg_temp.scan_probe($$update public.tickets set event_id='a6200000-0000-4000-8000-000000000002' where id=(select id from scan_ticket)$$),'invalid','contradictory foreign event is not wrong_event');
select is(pg_temp.scan_probe($$update public.tickets set ticket_tier_id='a6300000-0000-4000-8000-000000000003' where id=(select id from scan_ticket)$$),'invalid','tier contradiction');
select is(pg_temp.scan_probe($$update public.tickets set order_id=(select id from fulfillment_orders where kind='partial') where id=(select id from scan_ticket)$$),'invalid','order contradiction');
select is(pg_temp.scan_probe($$insert into public.tickets(order_id,order_item_id,event_id,organizer_id,ticket_tier_id,unit_sequence,status,admission_label,credential_hash) select order_id,order_item_id,event_id,organizer_id,ticket_tier_id,4,'valid',admission_label,decode(repeat('e',64),'hex') from scan_ticket$$),'invalid','extra source rejected');
select is(pg_temp.scan_probe($$insert into public.tickets(order_id,order_item_id,event_id,organizer_id,ticket_tier_id,unit_sequence,status,admission_label,credential_hash) select (select id from fulfillment_orders where kind='partial'),order_item_id,event_id,organizer_id,ticket_tier_id,4,'valid',admission_label,decode(repeat('e',64),'hex') from scan_ticket$$),'invalid','foreign-order extra source rejected');
select is(pg_temp.scan_probe($$update public.orders set status='requires_review' where id=(select order_id from scan_ticket)$$),'invalid','unpaid review order cannot admit');
select is(pg_temp.scan_probe($$update public.orders set reconciliation_status='requires_review' where id=(select order_id from scan_ticket)$$),'invalid','unreconciled paid order cannot admit');
create function pg_temp.foreign_review_probe() returns text language plpgsql as $$
declare v_outcome text;
begin
 update public.orders set reconciliation_status='requires_review' where id=(select order_id from scan_ticket);
 select pg_temp.scan('a6100000-0000-4000-8000-000000000002','a6200000-0000-4000-8000-000000000002') into v_outcome;
 raise exception using errcode='PT001';
exception when sqlstate 'PT001' then return v_outcome;
end;
$$;
select is(pg_temp.foreign_review_probe(),'invalid','unreconciled foreign credential is contradictory, not wrong_event');
select is(pg_temp.scan_probe($$update public.orders set paid_at=null where id=(select order_id from scan_ticket)$$),'invalid','missing paid truth cannot admit');
select is(pg_temp.scan_probe($$update public.events set status='draft' where id='a6200000-0000-4000-8000-000000000001'$$),'invalid','unpublished event cannot admit');
select is(pg_temp.scan_probe($$update public.events set status='cancelled' where id='a6200000-0000-4000-8000-000000000001'$$),'invalid','cancelled event with stale valid ticket cannot admit');
select is(pg_temp.scan_probe($$update public.events set starts_at=now()-interval '2 days',ends_at=now()-interval '1 day' where id='a6200000-0000-4000-8000-000000000001'$$),'invalid','ended event cannot admit');
select is(pg_temp.scan_probe($$update public.events set ends_at='infinity' where id='a6200000-0000-4000-8000-000000000001'$$),'invalid','nonfinite schedule cannot admit');
select is(pg_temp.scan_probe($$update public.tickets set status='refunded',refunded_at=now() where id=(select id from scan_ticket)$$),'refunded','stored refund terminal outcome');
select is(pg_temp.scan_probe($$update public.tickets set status='cancelled',cancelled_at=now() where id=(select id from scan_ticket)$$),'cancelled','stored cancellation terminal outcome');
select is(pg_temp.scan_probe($$update public.tickets set status='cancelled',cancelled_at=now() where id<>(select id from scan_ticket)$$),'invalid','contradictory sibling status cannot admit');
create function pg_temp.suppress_admission_write() returns trigger language plpgsql as $$begin return null; end;$$;
select is(pg_temp.scan_probe($$create trigger suppress_admission_write before update on public.tickets for each row execute function pg_temp.suppress_admission_write()$$),'invalid','no admitted result when guarded update returns no row');
set local role service_role;
select results_eq($$select * from public.server_redeem_paid_ticket('a6100000-0000-4000-8000-000000000001','a6200000-0000-4000-8000-000000000001',(select credential_hash from scan_ticket))$$,$$select 'admitted'::text,admission_label from scan_ticket$$,'first scan admits with snapshot label');
select is((select status from public.tickets where id=(select id from scan_ticket)),'used','admitted transaction writes used');
select ok((select used_at is not null from public.tickets where id=(select id from scan_ticket)),'admitted transaction writes used_at');
reset role;
create temporary table first_used as select used_at from public.tickets where id=(select id from scan_ticket);
select is(pg_temp.scan(),'already_used','replay cannot admit');
select is((select used_at from public.tickets where id=(select id from scan_ticket)),(select used_at from first_used),'replay preserves original used_at');
select is(pg_temp.scan_probe($$update public.orders set status='refunded',refunded_at=now(),reconciliation_status='requires_review' where id=(select order_id from scan_ticket)$$),'already_used','used precedence after financial changes');
select is(pg_temp.scan_probe($$update public.events set status='cancelled',starts_at=now()-interval '2 days',ends_at=now()-interval '1 day' where id='a6200000-0000-4000-8000-000000000001'$$),'already_used','used precedence after event cancellation and end');
select * from finish();
rollback;
