begin;
create extension if not exists pgtap with schema extensions;
set local search_path=public,extensions;
select no_plan();
insert into auth.users(id,email) values ('25000000-0000-4000-8000-000000000001','setup-a@example.invalid'),('25000000-0000-4000-8000-000000000002','setup-b@example.invalid');
insert into public.organizers(id,display_name) values ('25000000-0000-4000-8000-000000000001','Organizer A');
select set_config('request.jwt.claim.sub','25000000-0000-4000-8000-000000000001',true);
set local role authenticated;
select lives_ok($$select public.confirm_owned_storefront_handle('optional-logo',null)$$,'Optional logo does not block permanent handle');
select is((select handle from public.organizers),'optional-logo','Handle saved');
select lives_ok($$select public.confirm_owned_storefront_handle('optional-logo',null)$$,'Retry is idempotent');
select throws_ok($$select public.confirm_owned_storefront_handle('other-handle',null)$$,'P0001','HANDLE_IMMUTABLE','Permanent handle unchanged');
select lives_ok($$select public.save_owned_organizer_setup('{"displayName":"New name","organizerType":"Venue","bio":"","websiteUrl":"","baseCity":"Oakland"}',(select updated_at from public.organizers),null)$$,'Existing profile saves with canonical fields');
select is((select display_name from public.organizers),'New name','Name saved');
select is((select base_city from public.organizers),'Oakland','City saved');
select is((select handle from public.organizers),'optional-logo','Profile cannot change handle');
select ok((select onboarding_completed_at is not null from public.organizers),'Completion preserved');
select throws_ok($$select public.save_owned_organizer_setup('{"displayName":"Stale name"}',null,null)$$,'P0001','ORGANIZER_SETTINGS_CONFLICT','Stale create cannot overwrite');
select throws_ok($$select public.save_owned_organizer_setup('{"displayName":"New name"}',(select updated_at from public.organizers),'25000000-0000-4000-8000-000000000099')$$,'P0001','LOGO_NOT_OWNED','Unowned logo rejected');
select throws_ok($$select public.set_owned_storefront_published(true,(select updated_at from public.organizers))$$,'P0001','STOREFRONT_PUBLISH_REQUIREMENTS','Public storefront retains publication requirements');
reset role;
select set_config('request.jwt.claim.sub','25000000-0000-4000-8000-000000000002',true);
set local role authenticated;
select lives_ok($$select public.save_owned_organizer_setup('{"displayName":"Draft owner"}',null,null)$$,'First time profile saved');
select is((select handle from public.organizers),null::text,'Draft save never claims handle');
select is((select onboarding_completed_at from public.organizers),null::timestamptz,'Draft save never bypasses completion');
select throws_ok($$select public.confirm_owned_storefront_handle('optional-logo',null)$$,'P0001','HANDLE_TAKEN','Duplicate handle rejected');
select throws_ok($$select public.confirm_owned_storefront_handle('organizer',null)$$,'P0001','HANDLE_INVALID','Reserved handle rejected');
reset role;
set local role anon;
select throws_ok($$select public.save_owned_organizer_setup('{"displayName":"Anonymous"}',null,null)$$,'42501',null,'Anonymous write denied');
reset role;
select * from finish(); rollback;
