begin;
create extension if not exists pgtap with schema extensions;
set local search_path=public,extensions;
select no_plan();
select has_function('public','server_get_public_discovery_events',array['jsonb'],'bounded discovery RPC exists');
select has_function('public','server_consume_discovery_read_rate_limit',array['text'],'independent discovery limiter exists');
select function_privs_are('public','server_get_public_discovery_events',array['jsonb'],'anon',array[]::text[],'anonymous cannot bypass Edge quota');
select function_privs_are('public','server_get_public_discovery_events',array['jsonb'],'authenticated',array[]::text[],'organizer cannot bypass Edge quota');
select function_privs_are('public','server_get_public_discovery_events',array['jsonb'],'service_role',array['EXECUTE'],'service can read discovery');
select function_privs_are('public','server_consume_discovery_read_rate_limit',array['text'],'anon',array[]::text[],'anonymous cannot poison rate bucket');
select function_privs_are('public','server_consume_discovery_read_rate_limit',array['text'],'authenticated',array[]::text[],'organizer cannot poison rate bucket');
select ok(not has_table_privilege('anon','public.events','SELECT'),'anonymous base event table remains private');
select ok(not has_table_privilege('service_role','private.discovery_read_rate_buckets','SELECT'),'rate table stays inaccessible even to service role');
select ok(not has_function_privilege('anon','private.discovery_window(text,timestamptz)','EXECUTE'),'calendar helper private');
set local role anon;
select throws_ok($$select public.server_get_public_discovery_events('{"region":"sf_bay_area","when":"upcoming"}')$$,'42501',null,'anonymous direct invocation denied');
reset role;
select * from finish();
rollback;
