begin;
create extension if not exists pgtap with schema extensions;
set local search_path=public,extensions;
select no_plan();
\ir spec07_email_fixture.inc
update private.ticket_email_settings set enabled_at=null,worker_enabled=false;
\ir helpers/spec09_refund_setup.inc
select pg_temp.record_and_fulfill('spec10access','spec10access',id,session_id) from fulfillment_orders;
reset role;
insert into fulfillment_orders values('late',pg_temp.create_multi_item_order('a6400000-0000-4000-8000-000000000011',repeat('2',64),'cs_test_spec10late'),'cs_test_spec10late');
select * from public.server_redeem_paid_ticket('a6100000-0000-4000-8000-000000000001','a6200000-0000-4000-8000-000000000001',(select credential_hash from public.tickets order by id limit 1));
create temp table original_tickets as select id,credential_hash,status,used_at from public.tickets;
select public.cancel_owned_event('a6200000-0000-4000-8000-000000000001');
create function pg_temp.preview() returns jsonb language sql as $$select public.preview_owned_event_notice('a6200000-0000-4000-8000-000000000001','event_cancellation')$$;
select is(pg_temp.preview()->>'sourceCount','1','unpaid checkout excluded from cancellation audience');
select public.submit_owned_event_notice('a6200000-0000-4000-8000-000000000001','event_cancellation',pg_temp.preview()->>'previewToken','a6500000-0000-4000-8000-000000000011');
update private.ticket_email_settings set worker_enabled=true,enabled_at=now()-interval '1 minute';
create temp table claims as select public.server_claim_ticket_email() q;
create temp table prepared as select public.server_prepare_ticket_email_context((q->>'id')::uuid,(q->>'lease_id')::uuid) c from claims;
select is((select c->>'purpose' from prepared),'event_cancellation','existing worker prepares new cancellation purpose');
select is((select (c->>'expiresAt')::timestamptz-(c->>'preparedAt')::timestamptz from prepared),interval '30 days','status grant fixed thirty days from preparation');
select ok((select public.server_save_ticket_email_payload((q->>'id')::uuid,(q->>'lease_id')::uuid,repeat('a',64),pg_temp.envelope()) from claims),'payload prepared through shared encrypted envelope contract');
select is(public.server_read_event_status_access(repeat('a',64),repeat('e',64))->>'kind','ready','private cancellation link reads current source status');
select is(public.server_read_event_status_access(repeat('a',64),repeat('e',64))->'detail'->>'eventStatus','cancelled','event cancellation distinct from money');
select is(public.server_read_event_status_access(repeat('a',64),repeat('e',64))->'detail'->>'financialState','eligible','no automatic refund claim');
select is(public.server_read_event_status_access(repeat('a',64),repeat('e',64))->'detail'->>'canViewTickets','false','cancellation grant has no admission action');
select is(public.server_read_ticket_email_access(repeat('a',64),repeat('e',64),0,null),null::jsonb,'cancellation grant cannot open admission index');
select is(public.server_read_ticket_email_access(repeat('a',64),repeat('e',64),0,1),null::jsonb,'cancellation grant cannot mint admission');
select ok(not (public.server_read_event_status_access(repeat('a',64),repeat('e',64))::text ~ 'credential|stripe_|buyerEmail|access_hash|token_hash'),'buyer allowlist excludes secrets and PII');
select is((select count(*) from jsonb_array_elements(public.server_read_event_status_access(repeat('a',64),repeat('e',64))->'detail'->'tickets') t where t->>'status'='used'),1::bigint,'used admission remains history');
select ok((select public.server_begin_ticket_email_dispatch((q->>'id')::uuid,(q->>'lease_id')::uuid) is not null from claims),'existing dispatch boundary accepts canonical cancellation');
select public.server_finish_ticket_email_dispatch((q->>'id')::uuid,(q->>'lease_id')::uuid,'unknown') from claims;
select is(public.get_owned_event_notice_status('a6200000-0000-4000-8000-000000000001','event_cancellation')->>'unknown','1','transport timeout stays unknown');
select public.server_observe_ticket_email('spec10-delivered',(q->>'id')::uuid,'synthetic-spec10-delivery','delivered',now()) from claims;
select is(public.get_owned_event_notice_status('a6200000-0000-4000-8000-000000000001','event_cancellation')->>'accepted','1','provider acceptance separated from observation');
select is(public.get_owned_event_notice_status('a6200000-0000-4000-8000-000000000001','event_cancellation')->'observations'->>'delivered','1','verified observation retained');
select results_eq($$select id,credential_hash from public.tickets order by id$$,$$select id,credential_hash from original_tickets order by id$$,'notice delivery never changes admission identity');
select pg_temp.record_and_fulfill('spec10catchup','spec10catchup',id,session_id) from fulfillment_orders where kind='late';
select is(pg_temp.preview()->>'eligibleMessages','1','late received payment creates separately reviewed catch-up audience');
select is((select count(*) from private.ticket_email_outbox where purpose='event_cancellation'),1::bigint,'late payment does not auto-enqueue cancellation notice');
select public.submit_owned_event_notice('a6200000-0000-4000-8000-000000000001','event_cancellation',pg_temp.preview()->>'previewToken','a6500000-0000-4000-8000-000000000012');
select is((select count(*) from private.ticket_email_outbox where purpose='event_cancellation'),2::bigint,'catchup adds exactly one no-ticket source');
select is(pg_temp.preview()->>'eligibleMessages','0','catchup cannot duplicate original recipient source');
select public.server_revoke_ticket_email_grant((c->>'grantId')::uuid) from prepared;
select is(public.server_read_event_status_access(repeat('a',64),repeat('e',64)),null::jsonb,'revoked status access fails closed');
select is(public.server_read_event_status_access(repeat('b',64),repeat('e',64)),null::jsonb,'unknown status grant indistinguishable');
select ok(not has_function_privilege('authenticated','public.server_read_event_status_access(text,text)','execute'),'browser cannot bypass Edge access limits');
select set_config('request.jwt.claim.sub','b6100000-0000-4000-8000-000000000001',true);
select pg_temp.register(10,2);
select public.cancel_owned_event('b6200000-0000-4000-8000-000000000001');
select is(public.preview_owned_event_notice('b6200000-0000-4000-8000-000000000001','event_cancellation')->>'eligibleMessages','1','separate genuine free source has one notice for two tickets');
select is((select private.event_notice_detail('free_registration',id)->>'financialState' from public.free_registrations where event_id='b6200000-0000-4000-8000-000000000001'),'not_applicable','free buyer has no refund state');
select * from finish();rollback;
