begin;
create extension if not exists pgtap with schema extensions;
set local search_path=public,extensions;
select no_plan();
select private.configure_policy_environment('development');
\ir spec13_fixture.inc
insert into storage.objects(id,bucket_id,name,metadata,user_metadata) values('24000000-0000-4000-8000-000000000041','organizer-media','d1300000-0000-4000-8000-000000000001/24000000-0000-4000-8000-000000000041.png','{"size":100,"mimetype":"image/png"}','{"organizer_id":"d1300000-0000-4000-8000-000000000001"}');
select public.confirm_owned_storefront_handle('editor-proof','24000000-0000-4000-8000-000000000041');
set local role authenticated;
select lives_ok($$select public.set_owned_storefront_published(true,(select updated_at from public.organizers))$$,'Owner publishes eligible storefront');
select is(public.get_owned_storefront_editor()#>>'{status}','published','Owner reads own publication');
select ok(public.get_owned_storefront_preview() is not null,'Owner preview uses actual projection');
select throws_ok($$select public.set_owned_storefront_published(false,'2026-01-01')$$,'P0001','STOREFRONT_CONFLICT','Stale publication rejected');
select lives_ok($$select public.save_owned_storefront('{"name":"Discovery fixture owner","bio":"My events","city":"Oakland","websiteUrl":"https://example.org","logoId":"24000000-0000-4000-8000-000000000041","coverId":null,"accent":"violet","links":{"instagram":"https://instagram.com/organizer"},"featuredEventId":null}',(select updated_at from public.organizers))$$,'Owner saves bounded settings');
select lives_ok($$update public.organizers set bio='Existing profile write' where id=auth.uid()$$,'Existing profile writes still work with social links');
select throws_ok($$select public.save_owned_storefront('{"name":"Discovery fixture owner","bio":null,"city":null,"websiteUrl":"javascript:alert(1)","logoId":"24000000-0000-4000-8000-000000000041","coverId":null,"accent":null,"links":{},"featuredEventId":null}',(select updated_at from public.organizers))$$,'P0001','STOREFRONT_INVALID','Unsafe URL rejected');
select lives_ok($$select public.set_owned_storefront_published(false,(select updated_at from public.organizers))$$,'Owner unpublishes');
select is(public.get_public_organizer_storefront('editor-proof'),null::jsonb,'Draft hidden publicly');
select ok(public.get_owned_storefront_preview() is not null,'Draft still has private preview');
reset role;
set local role anon;
select throws_ok($$select public.get_owned_storefront_preview()$$,'42501',null,'Anonymous preview denied');
select throws_ok($$select public.get_owned_storefront_editor()$$,'42501',null,'Anonymous settings denied');
reset role;
select ok(not private.storefront_url_valid('https://user:pass@example.org'),'Credentials rejected');
select ok(not private.storefront_links_valid('{"facebook":"https://facebook.com/test"}'),'Unapproved social rejected');
select ok(not private.storefront_links_valid('{"instagram":"https://instagram.com.evil.org/test"}'),'Social host spoof rejected');
update public.organizers set website_url='https://user:pass@example.com' where handle='editor-proof';
select is(public.get_owned_storefront_editor()->'websiteUrl','null'::jsonb,'Legacy unsafe website cannot block editor loading');
select * from finish();rollback;
