begin;
create extension if not exists pgtap with schema extensions;
set local search_path=public,extensions;select no_plan();
\ir helpers/core_ticket_truth_lite_setup.inc
reset role;
grant select on fulfillment_orders to authenticated;
insert into storage.objects(id,bucket_id,name,metadata,user_metadata) values('24000000-0000-4000-8000-000000000061','organizer-media','a6100000-0000-4000-8000-000000000001/24000000-0000-4000-8000-000000000061.png','{"size":100,"mimetype":"image/png"}','{"organizer_id":"a6100000-0000-4000-8000-000000000001"}');
select set_config('request.jwt.claim.sub','a6100000-0000-4000-8000-000000000001',true);
select public.confirm_owned_storefront_handle('tracked-storefront','24000000-0000-4000-8000-000000000061');
update public.organizers set storefront_status='published' where handle='tracked-storefront';
set local role service_role;
select ok(public.server_record_storefront_telemetry(jsonb_build_object('kind','visit','handle','tracked-storefront','ref','launch','tokenHash',repeat('a',64)),repeat('b',64)),'Service records a public visit');
select ok(public.server_record_storefront_telemetry(jsonb_build_object('kind','visit','handle','tracked-storefront','ref','launch','tokenHash',repeat('a',64)),repeat('b',64)),'Visit retry accepted');
select ok(public.server_record_storefront_telemetry(jsonb_build_object('kind','start','eventId','a6200000-0000-4000-8000-000000000001','admissionType','paid','tokenHash',repeat('a',64)),repeat('b',64)),'Ticket start canonical ownership');
select ok(not public.server_record_storefront_telemetry(jsonb_build_object('kind','start','eventId','a6200000-0000-4000-8000-000000000002','admissionType','free','tokenHash',repeat('a',64)),repeat('b',64)),'Foreign/wrong-type start ignored');
reset role;
select is((select count(*) from private.storefront_visits),1::bigint,'One visit on retry');
-- Fixture reservations precede storefront fixture setup within this rollback transaction.
update private.storefront_visits set created_at=now()-interval '1 hour';
set local role service_role;
select public.server_associate_storefront_transaction('paid',(select client_request_id from public.orders where id=(select id from fulfillment_orders where kind='clean')),'a6200000-0000-4000-8000-000000000099',repeat('a',64));
reset role;select is((select count(*) from private.storefront_sources),0::bigint,'Request UUID alone cannot attach another event');set local role service_role;
select public.server_associate_storefront_transaction('paid',(select client_request_id from public.orders where id=(select id from fulfillment_orders where kind='clean')),'a6200000-0000-4000-8000-000000000001',repeat('a',64));
select public.server_associate_storefront_transaction('paid',(select client_request_id from public.orders where id=(select id from fulfillment_orders where kind='clean')),'a6200000-0000-4000-8000-000000000001',repeat('c',64));
reset role;
select is((select count(*) from private.storefront_sources where token_hash=repeat('a',64)),1::bigint,'Retry cannot reassign source');
set local role authenticated;
select is((public.get_owned_storefront_insights()->>'paidOrders')::integer,0,'Pending checkout never counts as paid');
reset role;set local role service_role;
select is(pg_temp.record_and_fulfill('storefronttracked','storefronttracked',(select id from fulfillment_orders where kind='clean'),'cs_test_integrityclean')->>'order_status','paid','Canonical payment completes');
reset role;set local role authenticated;
select is((public.get_owned_storefront_insights()->>'paidOrders')::integer,1,'Completed paid truth counted once');
reset role;
select is((public.get_owned_storefront_insights()#>>'{grossByCurrency,0,amountMinor}')::bigint,(select sum(subtotal_minor)::bigint from public.order_items where order_id=(select id from fulfillment_orders where kind='clean')),'Gross uses canonical item totals');
reset role;
select set_config('request.jwt.claim.sub','a6100000-0000-4000-8000-000000000002',true);
set local role authenticated;
select is((public.get_owned_storefront_insights()->>'visits')::integer,0,'Other organizer sees no visits');
select throws_ok($$select * from private.storefront_visits$$,'42501',null,'No direct private telemetry reads');
reset role;set local role anon;
select throws_ok($$select public.get_owned_storefront_insights()$$,'42501',null,'No public analytics');
select throws_ok($$select public.server_associate_storefront_transaction('paid',gen_random_uuid(),gen_random_uuid(),null)$$,'42501',null,'Public cannot attach transaction');
reset role;
\ir free_registration_fixture.inc
insert into private.storefront_visits values(repeat('d',64),'b6100000-0000-4000-8000-000000000001','rsvp',now()-interval '1 hour');
select is(pg_temp.register(1)->>'kind','confirmed','Existing RSVP succeeds');
select public.server_associate_storefront_transaction('free',(select request_id from public.free_registrations limit 1),'b6200000-0000-4000-8000-000000000001',repeat('d',64));
select public.server_associate_storefront_transaction('free',(select request_id from public.free_registrations limit 1),'b6200000-0000-4000-8000-000000000001',repeat('a',64));
select is((select count(*) from private.storefront_sources where kind='free' and token_hash=repeat('d',64)),1::bigint,'RSVP association is durable and idempotent');
select is((select count(*) from public.tickets where registration_id is not null),2::bigint,'Measurement does not alter admission truth');
update private.storefront_visits set created_at=now()-interval '31 days' where token_hash=repeat('d',64);
select is(pg_temp.register(2,1)->>'kind','confirmed','Expired context does not reject RSVP');
select public.server_associate_storefront_transaction('free',(select request_id from public.free_registrations where quantity=1),'b6200000-0000-4000-8000-000000000001',repeat('d',64));
select is((select count(*) from private.storefront_sources where kind='free' and token_hash is null),1::bigint,'Expired context creates unattributed source');
select * from finish();rollback;
