import {test,expect,type Page} from '@playwright/test'
import {readFileSync,mkdirSync} from 'node:fs'
import {execFileSync} from 'node:child_process'
const f=JSON.parse(readFileSync('.superpowers/event-import-proof/browser.json','utf8')) as {actors:Record<string,string>;tokens:Record<string,string>;api:string;edge:string;origin:string;anon:string}
async function connect(page:Page,actor:string){
 await page.route('**/*',async route=>{const r=route.request(),u=new URL(r.url());if(u.origin==='https://event-import-proof-local.supabase.co'){
 if(r.method()==='OPTIONS')return route.fulfill({status:204,headers:{'access-control-allow-origin':f.origin,'access-control-allow-headers':'*','access-control-allow-methods':'*'}})
 const response=await route.fetch({url:(u.pathname.startsWith('/functions/')?f.edge:f.api)+u.pathname+u.search,headers:{...r.headers(),origin:f.origin}});return route.fulfill({response,headers:{...response.headers(),'access-control-allow-origin':f.origin}})
 }if(u.origin!==f.origin&&!['data:','blob:'].includes(u.protocol))return route.abort('blockedbyclient');return route.continue()})
 await page.addInitScript(({id,token})=>localStorage.setItem('sb-event-import-proof-local-auth-token',JSON.stringify({access_token:token,refresh_token:'synthetic',expires_at:Math.floor(Date.now()/1000)+12000,expires_in:12000,token_type:'bearer',user:{id,email:'synthetic@example.invalid',aud:'authenticated',role:'authenticated',app_metadata:{},user_metadata:{},created_at:'2026-01-01T00:00:00Z'}})),{id:f.actors[actor],token:f.tokens[actor]})
}
const header='title,description,category,start_date,start_time,end_date,end_time,venue_name,address,city,postal_code,capacity,notes'
const day=new Date(Date.now()+30*86400000).toISOString().slice(0,10)
function csv(title:string,address='1 Market St',category='community'){return `${title},A community gathering for neighbors and friends.,${category},${day},12:00,${day},14:00,Civic Hall,${address},San Francisco,94105,,PRIVATE_PROVENANCE_CANARY`}
async function upload(page:Page,name:string,content:string){await page.getByLabel('CSV file').setInputFiles({name,mimeType:'text/csv',buffer:Buffer.from(content)});await page.getByRole('button',{name:'Upload CSV',exact:true}).click();await expect(page.getByRole('heading',{name,exact:true})).toBeVisible()}
async function shot(page:Page,name:string){mkdirSync('.superpowers/event-import-proof/screens',{recursive:true});await page.evaluate(()=>document.fonts.ready);await page.screenshot({path:`.superpowers/event-import-proof/screens/${name}.png`,fullPage:true});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)}
for(const actor of ['moderator','other','inactive','buyer'])test(`${actor} denied`,async({page})=>{await connect(page,actor);await page.goto('/moderation/event-imports');await expect(page.getByRole('heading',{name:actor==='moderator'?'Admin access required':'Moderation access required'})).toBeVisible();await expect(page.getByLabel('CSV file')).toHaveCount(0)})
for(const width of [390,1440])test(`upload/review/retry/reload/handoff at ${width}`,async({page,browser})=>{
 await page.setViewportSize({width,height:900});const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});await connect(page,'admin');await page.goto('/moderation/event-imports');await expect(page.getByRole('heading',{name:'CSV event imports'})).toBeVisible();await page.getByRole('button',{name:'Download CSV template'}).focus();await expect(page.getByRole('button',{name:'Download CSV template'})).toBeFocused();await shot(page,`upload-${width}`)
 await upload(page,`malformed-${width}.csv`,header+'\n"unfinished');await expect(page.getByRole('alert')).toContainText('CSV STRUCTURE INVALID');await page.getByRole('link',{name:'All imports'}).click()
 const title=`Browser ${width} ${Date.now()}`;await upload(page,`review-${width}.csv`,header+'\n'+[csv(title),csv(title),csv('Ambiguous '+title,'Ambiguous Place'),csv('Retry '+title,'Retry '+title),csv('Invalid '+title,'1 Market St','bogus'),csv('<script>alert(1)</script> '+title)].join('\n'))
 const batch=page.url();await page.getByRole('button',{name:'Continue',exact:true}).click();await expect(page.getByRole('button',{name:'Continue',exact:true})).toBeEnabled();await expect(page.getByText('Possible duplicate',{exact:true})).toBeVisible();await expect(page.getByText('Needs review',{exact:true})).toBeVisible();await page.reload();await expect(page.getByText('Possible duplicate',{exact:true})).toBeVisible();await page.getByLabel('Select row 2',{exact:true}).check();await page.getByRole('button',{name:'Import Selected (1)',exact:true}).click();await expect(page.getByText('Imported',{exact:true})).toBeVisible();await expect(page.getByRole('link',{name:'Edit draft'})).toHaveCount(0);await shot(page,`review-${width}`)
 await page.getByRole('button',{name:'Import anyway',exact:true}).click();await expect(page.getByRole('button',{name:'Continue',exact:true})).toBeEnabled();if(await page.getByRole('button',{name:'Import anyway',exact:true}).count()) {await page.getByRole('button',{name:'Import anyway',exact:true}).click();await expect(page.getByRole('button',{name:'Continue',exact:true})).toBeEnabled()}await page.getByLabel('Select row 3',{exact:true}).check();await page.getByRole('button',{name:'Import Selected (1)',exact:true}).click();await expect(page.getByText('Imported',{exact:true})).toHaveCount(2)
 // Force this synthetic transport failure to exhausted state, then use the real Retry control.
 const batchId=new URL(batch).pathname.split('/').at(-1)!;expect(batchId).toMatch(/^[a-f0-9-]{36}$/);
 execFileSync('docker',['exec','-i','supabase_db_wheretoo-event-import','psql','-X','-U','postgres','-v','ON_ERROR_STOP=1'],{input:`update private.event_import_rows set state='failed',attempts=5,failure_code='PROVIDER_RETRIES_EXHAUSTED' where batch_id='${batchId}' and record_number=5 and state='pending';`});
 await page.getByRole('button',{name:'Refresh',exact:true}).click();await page.getByRole('button',{name:'Retry',exact:true}).click();await expect(page.getByRole('button',{name:'Continue',exact:true})).toBeEnabled();
 // Continue resumes the retry through the same injected provider and real row lease.
 await expect.poll(async()=>{await page.getByRole('button',{name:'Continue',exact:true}).click();await expect(page.getByRole('button',{name:'Continue',exact:true})).toBeEnabled();return page.getByLabel('Select row 5',{exact:true}).isEnabled()},{timeout:15000,intervals:[500,1000,2000]}).toBe(true);await page.getByRole('button',{name:'Select ready rows on this page'}).click();await page.getByRole('button',{name:/Import Selected \([1-9]/}).click();await expect(page.getByRole('link',{name:'View imported event'})).toHaveCount(4)
 await page.getByRole('link',{name:'View imported event'}).first().click();await expect(page).toHaveURL(/event-imports\/drafts\//);await expect(page.getByRole('heading',{name:title,exact:true})).toBeVisible();const draft=page.url();await expect(page.getByText('Awaiting official organizer review',{exact:true})).toBeVisible();await expect(page.getByRole('link',{name:'Edit draft'})).toHaveCount(0);await shot(page,`handoff-${width}`)
 const context=await browser.newContext({viewport:{width,height:900}}),owner=await context.newPage();await connect(owner,'owner');await owner.goto(draft);await expect(owner.getByRole('link',{name:'Edit draft'})).toBeVisible();await owner.getByRole('link',{name:'Edit draft'}).click();await expect(owner).toHaveURL(/\/organizer\/events\/[^/]+\/edit/);await expect(owner.getByLabel('Event title',{exact:true})).toHaveValue(title);await shot(owner,`owner-editor-${width}`);await context.close()
 await page.goto(batch);await page.getByText('Cancel remaining import',{exact:true}).click();await page.getByRole('button',{name:'Confirm cancellation'}).click();await expect(page.getByText('cancelled',{exact:true})).toBeVisible();await expect(page.getByRole('link',{name:'View imported event'})).toHaveCount(4);expect(errors).toEqual([])
})

test('review pagination stays at fifty rows',async({page})=>{
 const fixture=JSON.parse(readFileSync('.superpowers/sdd/2026-09-24-csv-event-import-v1/scale.json','utf8')) as {batch:string};await connect(page,'admin');await page.goto('/moderation/event-imports/'+fixture.batch);await expect(page.locator('tbody tr')).toHaveCount(50);await page.getByRole('button',{name:'Next',exact:true}).click();await expect(page.getByText('Rows 51–100 of 500',{exact:true})).toBeVisible();await expect(page.locator('tbody tr')).toHaveCount(50);
});
