// Version-pinned SDK contract tests; isolated memory storage and no provider network.
const {test}=require('node:test'),assert=require('node:assert/strict');
const {AuthClient}=require('@supabase/supabase-js');
const deferred=()=>{let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b});return {promise,resolve,reject}};
const turn=()=>new Promise(resolve=>setImmediate(resolve));
function client(extra={}){return new AuthClient({url:'https://auth.invalid/auth/v1',persistSession:false,autoRefreshToken:false,detectSessionInUrl:false,skipAutoInitialize:true,fetch:()=>{throw Error('Unexpected provider call')},...extra})}
function readiness(result){assert.ok(result.data.subscription.unsubscribe);assert.ok(result.ready instanceof Promise,'approved SDK ready contract is installed');return result.ready}
test('ready covers custom-lock async callback and remains data-compatible',async()=>{let held=false;const gate=deferred(),entered=deferred();const auth=client({lock:async(_n,_t,fn)=>{held=true;try{return await fn()}finally{held=false}}});const result=auth.onAuthStateChange(async(event)=>{assert.equal(event,'INITIAL_SESSION');entered.resolve();await gate.promise});const ready=readiness(result);let settled=false;void ready.then(()=>settled=true);await entered.promise;assert.equal(held,true);assert.equal(settled,false);gate.resolve();assert.deepEqual(await ready,{error:null});assert.equal(held,false);result.data.subscription.unsubscribe();await auth.dispose()});
test('no-custom-lock branch waits for callback completion',async()=>{const auth=client(),gate=deferred(),entered=deferred();const result=auth.onAuthStateChange(async()=>{entered.resolve();await gate.promise});const ready=readiness(result);let settled=false;void ready.then(()=>settled=true);await entered.promise;assert.equal(settled,false);gate.resolve();assert.deepEqual(await ready,{error:null});await auth.dispose()});
test('initialization rejection is fulfilled error and removes the subscriber',async()=>{const auth=client();const gate=deferred();auth.initializePromise=gate.promise;let calls=0;const result=auth.onAuthStateChange(()=>calls++);const ready=readiness(result);gate.reject(Error('synthetic initialization'));const status=await ready;assert.match(status.error.message,/synthetic initialization/);assert.equal(calls,0);assert.equal(auth.stateChangeEmitters.size,0);auth.initializePromise=Promise.resolve({error:null});await auth.dispose()});
test('lock rejection is fulfilled error with no callback or storage write',async()=>{let writes=0,calls=0;const auth=client({lock:async()=>{throw Error('synthetic lock')},storage:{getItem:()=>null,setItem:()=>writes++,removeItem:()=>writes++}});const result=auth.onAuthStateChange(()=>calls++);const status=await readiness(result);assert.match(status.error.message,/synthetic lock/);assert.equal(calls,0);assert.equal(writes,0);assert.equal(auth.stateChangeEmitters.size,0);await auth.dispose()});
test('unsubscribe-before-ready settles without a removed callback',async()=>{const auth=client(),gate=deferred();auth.initializePromise=gate.promise;let calls=0;const result=auth.onAuthStateChange(()=>calls++);const ready=readiness(result);result.data.subscription.unsubscribe();gate.resolve({error:null});assert.deepEqual(await ready,{error:null});assert.equal(calls,0);await auth.dispose()});
test('propagated callback failure fulfills readiness error and unsubscribes',async()=>{const auth=client();const result=auth.onAuthStateChange(()=>{throw Error('synthetic callback')});const status=await readiness(result);assert.match(status.error.message,/synthetic callback/);assert.equal(auth.stateChangeEmitters.size,0);await auth.dispose()});
test('ignored readiness has no unhandled rejection',async()=>{const errors=[];const onError=e=>errors.push(e);process.on('unhandledRejection',onError);const auth=client({lock:async()=>{throw Error('synthetic ignored-ready lock')}});const result=auth.onAuthStateChange(()=>{});readiness(result);await turn();await turn();assert.deepEqual(errors,[]);assert.equal(auth.stateChangeEmitters.size,0);await auth.dispose();process.off('unhandledRejection',onError)});
