// Isolated completion-order proof. All credentials are synthetic and all network is intercepted.
const { createRequire } = require('node:module')
const assert = require('node:assert/strict')
const path = require('node:path')
const root = path.resolve(__dirname, '../..')
const req = createRequire(path.join(root, 'package.json'))
const { chromium } = req('@playwright/test')
const esbuild = req('./node_modules/.pnpm/esbuild@0.28.2/node_modules/esbuild')
;(async () => {
 const bundle = await esbuild.build({ stdin:{ contents:`export { supabase } from './src/lib/supabase/client'; export { signInOrganizer } from './src/features/auth/auth.api'; export { SessionProvider, useSession } from './src/features/auth/SessionProvider'; export { SignOutProvider, useSignOut } from './src/features/auth/SignOutProvider'; export { QueryClient, QueryClientProvider } from '@tanstack/react-query'; export { createRoot } from 'react-dom/client'; export * as React from 'react';`, resolveDir:root }, bundle:true, format:'iife', globalName:'AppAuth', platform:'browser', jsx:'automatic', write:false, define:{'import.meta.env':JSON.stringify({VITE_SUPABASE_URL:'https://auth-spec14.invalid',VITE_SUPABASE_PUBLISHABLE_KEY:'sb_publishable_audit_dummy',VITE_MAPBOX_ACCESS_TOKEN:'pk.synthetic',VITE_STRIPE_PUBLISHABLE_KEY:'pk_test_synthetic'})} })
 const browser=await chromium.launch({headless:true}); const context=await browser.newContext(); let unexpected=0
 await context.route('**/*', route=>{ if(route.request().url().startsWith('https://spec14.invalid/')) return route.fulfill({contentType:'text/html',body:'<!doctype html><div id="root"></div>'}); unexpected++; return route.abort() })
 const page=await context.newPage(); await page.goto('https://spec14.invalid/')
 await page.evaluate(()=>{ window.audit=[]; function user(){return {id:'00000000-0000-4000-8000-000000000001',aud:'authenticated',role:'authenticated',email:'a@example.invalid',app_metadata:{},user_metadata:{},created_at:new Date().toISOString()}}; window.fetch=async(input,options)=>{const u=new URL(input); audit.push(u.pathname); if(u.pathname==='/auth/v1/token') return new Response(JSON.stringify({access_token:'synthetic-A',refresh_token:'synthetic-refresh-A',token_type:'bearer',expires_in:3600,user:user()}),{status:200,headers:{'content-type':'application/json'}}); if(u.pathname==='/auth/v1/logout') return new Response(null,{status:204}); throw new Error('unexpected '+u.pathname)}})
 await page.addScriptTag({content:bundle.outputFiles[0].text})
 await page.evaluate(()=>{ window.client=new AppAuth.QueryClient(); function Probe(){const s=AppAuth.useSession(); const c=AppAuth.useSignOut(); window.controller=c; return AppAuth.React.createElement('p',{id:'state'},s.status==='authenticated'?s.user.id:s.status)}; AppAuth.createRoot(document.querySelector('#root')).render(AppAuth.React.createElement(AppAuth.QueryClientProvider,{client},AppAuth.React.createElement(AppAuth.SignOutProvider,null,AppAuth.React.createElement(AppAuth.SessionProvider,{queryClient:client},AppAuth.React.createElement(Probe))))) })
 await page.waitForFunction(()=>document.querySelector('#state')?.textContent==='anonymous')
 await page.evaluate(()=>AppAuth.signInOrganizer({email:'a@example.invalid',password:'synthetic'}))
 await page.waitForFunction(()=>document.querySelector('#state')?.textContent?.endsWith('0001'))
 const result=await page.evaluate(async()=>{ const expected=(await AppAuth.supabase.auth.getSession()).data.session; const outcome=await controller.signOut(expected); window.completedSignOut=outcome; return {localSignedOut:outcome.localSignedOut,remoteRevoked:outcome.remoteRevoked,isCurrentImmediately:outcome.isCurrent(),stateImmediately:document.querySelector('#state')?.textContent, error:controller.error,notice:controller.notice} })
 await page.waitForFunction(()=>document.querySelector('#state')?.textContent==='anonymous')
 await page.waitForFunction(()=>controller.notice==='You have signed out.')
 result.isCurrentAfterAnonymous=await page.evaluate(()=>completedSignOut.isCurrent()); assert.equal(result.isCurrentAfterAnonymous,true)
 result.browserVersion=browser.version(); result.stateEventually=await page.$eval('#state',e=>e.textContent); result.unexpected=unexpected; console.log(JSON.stringify(result,null,2)); await context.close(); await browser.close(); assert.equal(result.localSignedOut,true); assert.equal(result.isCurrentImmediately,true)
})().catch(e=>{console.error(e);process.exitCode=1})
