import { expect, test } from '@playwright/test'
import { connect, emailLink, fixture, localEdge, messages, screenshot, sql, work } from './support/spec07Harness'

test.describe.configure({ mode: 'serial' })
let originalFreeQr = ''
let originalPaidQr = ''
test('automatic delivery retains legacy paid and namespaced free collections', async ({ page }) => {
  const f = fixture(); await connect(page)
  await work(page)
  expect(await messages(page)).toHaveLength(2)
  for (const [token, count] of [[f.paidToken, 3], [f.freeToken, 2]] as const) {
    await page.goto('/tickets/' + token)
    await expect(page.getByRole('heading', { name: 'Ticket wallet' })).toBeVisible()
    await expect(page.locator('.buyer-wallet-row')).toHaveCount(count)
    await page.locator('.buyer-wallet-row').last().click()
    await expect(page.getByLabel('Admission QR code')).toHaveCount(1)
    const qr = await page.getByLabel('Admission QR code').evaluate(node => (node as HTMLCanvasElement).toDataURL())
    if (token === f.freeToken) originalFreeQr = qr
    else originalPaidQr = qr
    await page.getByRole('link', { name: 'Back to all tickets' }).click()
    await expect(page.getByLabel('Admission QR code')).toHaveCount(0)
  }
  const paidMessage = (await messages(page)).find(m => /harbor lights/i.test(m.text))!
  await page.goto(emailLink(paidMessage))
  await expect(page.getByRole('heading', { name: 'Ticket wallet' })).toBeVisible()
  expect(page.url()).not.toContain('#')
  expect(page.url()).not.toContain('em1_')
  const result = sql("select round(extract(epoch from (expires_at-prepared_at))/86400) from private.ticket_email_grants where purpose='initial' and scheduled_end_at>now()+interval '59 days';")
  expect(result).toContain('61')
})
test('public recovery is neutral and opens a fixed mixed paid/free snapshot in a fresh browser', async ({ page, browser }) => {
  await connect(page)
  await page.goto('/tickets/recover')
  await page.getByLabel('Email address').fill('pat@example.invalid')
  await page.getByRole('button', { name: 'Send me my tickets' }).click()
  await expect(page.getByRole('heading', { name: 'Check your email' })).toBeVisible()
  const neutral = await page.getByRole('status').innerText()
  await screenshot(page, 'recovery-requested-390')
  await work(page)
  const all = await messages(page), recovery = all[all.length - 1]!
  const context = await browser.newContext({ viewport: { width: 390, height: 844 } })
  const fresh = await context.newPage(); await connect(fresh)
  await fresh.goto(emailLink(recovery))
  await expect(fresh.getByRole('heading', { name: 'Your tickets', exact: true })).toBeVisible()
  await expect(fresh.locator('.delivery-index-list li')).toHaveCount(2)
  expect(fresh.url()).not.toContain('#')
  await screenshot(fresh, 'recovery-index-390')
  await fresh.getByRole('link', { name: /Community Night/ }).click()
  await expect(fresh.getByRole('heading', { name: 'Ticket wallet' })).toBeVisible()
  await expect(fresh.getByRole('link', { name: /Ticket 1,.*Already used/ })).toBeVisible()
  await fresh.getByRole('link', { name: /Ticket 2,.*Valid/ }).click()
  await expect(fresh.getByLabel('Admission QR code')).toHaveCount(1)
  expect(await fresh.getByLabel('Admission QR code').evaluate(node => (node as HTMLCanvasElement).toDataURL())).toBe(originalFreeQr)
  await screenshot(fresh, 'recovered-valid-ticket-390')
  await fresh.getByRole('link', { name: 'Back to all tickets' }).click()
  await fresh.getByRole('link', { name: /Ticket 1,.*Already used/ }).click()
  await expect(fresh.getByLabel('Admission QR code')).toHaveCount(0)
  await expect(fresh.getByText(/Already used/).first()).toBeVisible()
  await screenshot(fresh, 'recovered-used-ticket-390')
  await fresh.reload()
  await expect(fresh.getByLabel('Admission QR code')).toHaveCount(0)
  await fresh.getByRole('link', { name: 'Back to collections' }).click()
  await fresh.getByRole('link', { name: /Harbor Lights/ }).click()
  await expect(fresh.locator('.buyer-wallet-row')).toHaveCount(3)
  await fresh.locator('.buyer-wallet-row').last().click()
  await expect(fresh.getByLabel('Admission QR code')).toHaveCount(1)
  expect(await fresh.getByLabel('Admission QR code').evaluate(node => (node as HTMLCanvasElement).toDataURL())).toBe(originalPaidQr)
  await context.close()
  await page.getByRole('button', { name: 'Use a different email' }).click()
  await page.getByLabel('Email address').fill('no-match@example.invalid')
  await page.getByRole('button', { name: 'Send me my tickets' }).click()
  await expect(page.getByRole('status')).toHaveText(neutral)
  const before = (await messages(page)).length; await work(page)
  expect(await messages(page)).toHaveLength(before)
})
test('organizer resend keeps request identity through remount and reconciles lost provider response', async ({ page }) => {
  const f = fixture(); await connect(page, f.owner)
  await page.goto(`/organizer/events/${f.freeEvent}/registrations/${f.registration}`)
  await expect(page.getByRole('heading', { name: 'Registration details' })).toBeVisible()
  await page.getByRole('button', { name: 'Resend tickets', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('pat@example.invalid')
  await page.getByRole('button', { name: 'Confirm and resend' }).click()
  await expect(page.getByRole('dialog')).toContainText('Ticket email queued')
  const remembered = await page.evaluate(() => sessionStorage.getItem('wheretoo:ticket-resends:v1'))
  await work(page, 'lost')
  await page.getByRole('button', { name: 'Check status' }).click()
  await expect(page.getByRole('dialog')).toContainText('Send status unknown')
  await screenshot(page, 'resend-unknown-390')
  await page.reload()
  await page.getByRole('button', { name: 'Resend tickets', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('Send status unknown')
  expect(await page.evaluate(() => sessionStorage.getItem('wheretoo:ticket-resends:v1'))).toBe(remembered)
  const all = await messages(page), last = all[all.length - 1]!
  expect((await page.request.post(localEdge + '/__spec07/observe', { data: { attemptId: last.attemptId } })).ok()).toBeTruthy()
  await page.getByRole('button', { name: 'Check status' }).click()
  await expect(page.getByRole('dialog')).toContainText('Email delivery reported')
  await screenshot(page, 'resend-reconciled-390')
  await expect(page.getByRole('button', { name: 'Confirm and resend' })).toHaveCount(0)
})
test('paid resend definite failure preserves initial status and signed evidence wins a lost response', async ({ page }) => {
  const f = fixture(); await connect(page, f.paidOwner)
  // Synthetic cooldown advancement only; no production profile is activated.
  sql("update private.ticket_email_rate_events set at=at-interval '2 minutes' where lane in ('resend_recipient','resend_source');")
  await page.goto(`/organizer/events/${f.paidEvent}/orders/${f.paidOrder}`)
  await page.getByRole('button', { name: 'Resend tickets', exact: true }).click()
  await page.getByRole('button', { name: 'Confirm and resend' }).click()
  await expect(page.getByRole('dialog')).toContainText('Ticket email queued')
  await work(page, 'failed')
  await page.getByRole('button', { name: 'Check status' }).click()
  await expect(page.getByRole('dialog')).toContainText('Couldn’t resend tickets')
  await screenshot(page, 'paid-resend-failed-390')
  const initial = await page.request.post(localEdge + '/functions/v1/ticket-email-status', { headers: { origin: 'http://127.0.0.1:3027' }, data: { collectionBearer: f.paidToken } })
  expect(await initial.json()).toMatchObject({ state: 'accepted' })
  sql("update private.ticket_email_rate_events set at=at-interval '2 minutes' where lane in ('resend_recipient','resend_source');")
  await page.getByRole('button', { name: 'Request another email' }).click()
  await expect(page.getByRole('dialog')).toContainText('Ticket email queued')
  await work(page, 'webhook_before_response')
  await page.getByRole('button', { name: 'Check status' }).click()
  await expect(page.getByRole('dialog')).toContainText('Email delivery reported')
  await screenshot(page, 'paid-resend-reconciled-390')
})
test('wrong owner cannot read registration or resend', async ({ page }) => {
  const f = fixture(); await connect(page, f.paidOwner)
  await page.goto(`/organizer/events/${f.freeEvent}/registrations/${f.registration}`)
  await expect(page.getByRole('heading', { name: 'Registration unavailable' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Resend tickets', exact: true })).toHaveCount(0)
})
test('public recovery and invalid access remain usable at 320, 390, 768 and 1440 pixels', async ({ page }) => {
  await connect(page)
  for (const width of [320, 390, 768, 1440]) {
    await page.setViewportSize({ width, height: 900 })
    await page.goto('/tickets/recover')
    await expect(page.getByLabel('Email address')).toBeVisible()
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy()
    await screenshot(page, 'recovery-form-' + width)
  }
  await page.goto('/ticket-access#bad-token')
  await expect(page.getByRole('heading', { name: 'Ticket link unavailable' })).toBeVisible()
  expect(page.url()).not.toContain('#')
})
test('email flows preserve every original ticket row including credential hashes and Used history', async () => {
  const f = fixture()
  const result = sql("select jsonb_agg(to_jsonb(t) order by t.id) from public.tickets t where event_id in ('c7200000-0000-4000-8000-000000000001','c8200000-0000-4000-8000-000000000001');")
  const line = result.split('\n').find(row => row.trim().startsWith('['))
  expect(JSON.parse(line!.trim())).toEqual(f.tickets)
})
