// Regenerate the approved SDK outputs in memory; never write the installed package.
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),ts=require('typescript');
const sdk=path.dirname(require.resolve('@supabase/supabase-js'));
const root=path.resolve(path.dirname(require.resolve('@supabase/auth-js',{paths:[sdk]})),'../..');
test('published CJS/ESM declarations and all four maps regenerate exactly from the maintained source',()=>{
 assert.equal(JSON.parse(fs.readFileSync(path.join(root,'package.json'),'utf8')).version,'2.112.3');
 const errors=[];
 for(const [folder,module]of [['main',ts.ModuleKind.CommonJS],['module',ts.ModuleKind.ESNext]]){
  const options={target:ts.ScriptTarget.ES2017,module,moduleResolution:ts.ModuleResolutionKind.Node10,ignoreDeprecations:'6.0',strict:true,esModuleInterop:true,importHelpers:true,declaration:true,declarationMap:true,sourceMap:true,rootDir:path.join(root,'src'),outDir:path.join(root,'dist',folder),skipLibCheck:true,types:['node'],useDefineForClassFields:false};
  const host=ts.createCompilerHost(options),outputs=new Map();host.writeFile=(name,text)=>outputs.set(path.resolve(name),text);
  const program=ts.createProgram(ts.sys.readDirectory(path.join(root,'src'),['.ts']),options,host);const diagnostics=ts.getPreEmitDiagnostics(program);errors.push(...diagnostics);program.emit();
  for(const ext of ['.js','.d.ts','.js.map','.d.ts.map']){
   const name=path.join(root,'dist',folder,'GoTrueClient'+ext);assert.equal(outputs.get(name),fs.readFileSync(name,'utf8'),folder+ext+' regenerated bytes');
   if(ext.endsWith('.map'))assert.deepEqual(JSON.parse(outputs.get(name)).sources,['../../src/GoTrueClient.ts']);
  }
 }
 // Upstream source targets TS5.8 DOM; installed TS6 introduces this already reproduced baseline mismatch.
 // Do not suppress any new diagnostic, or call this a passing full upstream typecheck.
 for(const error of errors){assert.equal(error.code,2430);assert.ok(error.file.fileName.endsWith('/src/lib/webauthn.dom.ts'))}
 console.log(JSON.stringify({compiler:ts.version,distributionFiles:8,exactRegeneration:true,upstreamSourceTypecheck:errors.length?'pre-existing-TS6-DOM-incompatibility':'passed',knownBaselineDiagnostics:errors.length}));
});
