import { randomUUID } from 'node:crypto'
import { expect, test } from '@playwright/test'
import { fixture, capture } from './support/spec11Harness'

test('configured help/legal and manual closure confirm, cancel, safe mail handoff without deletion', async ({ page }) => {
  const f = await fixture(page)
  await page.goto('/organizer/settings/help')
  await expect(page.getByRole('link', { name: 'Open email app ↗' })).toHaveCount(2)
  await expect(page.getByRole('link', { name: 'Read Terms ↗' })).toHaveAttribute('href', 'https://policies.example.invalid/terms')
  await expect(page.getByRole('link', { name: 'Read Privacy ↗' })).toHaveAttribute('href', 'https://policies.example.invalid/privacy')
  await capture(page, 'help-configured-390')
  await page.goto('/organizer/settings/actions')
  await page.getByRole('button', { name: 'Request account closure', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('does not close your account')
  await page.getByLabel('Reason (optional)').fill('Please review closure of my organizer account.')
  await expect(page.getByRole('link', { name: 'Open email app', exact: true })).toBeVisible()
  await capture(page, 'closure-confirm-390')
  await page.getByRole('button', { name: 'Cancel', exact: true }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await page.getByRole('button', { name: 'Request account closure', exact: true }).click()
  await expect(page.getByLabel('Reason (optional)')).toHaveValue('')
  const handoff = page.getByRole('link', { name: 'Open email app', exact: true })
  await expect(handoff).toBeVisible()
  const href = new URL((await handoff.getAttribute('href'))!)
  expect(href.pathname).toBe('review@example.invalid')
  expect(href.searchParams.get('body')).toBe('Organizer: Night Market Collective\nCurrent login email: private@example.invalid\nReason: ')
  // Exercise app handoff state, suppress only OS mail-client launch. No email is sent.
  await handoff.evaluate(node => node.addEventListener('click', event => event.preventDefault(), { once: true }))
  await handoff.click()
  await expect(page.getByRole('status')).toContainText('No request has been submitted by Wheretoo.')
  expect(f.state.writes).toBe(0); expect(f.state.signOuts).toBe(0); expect(f.state.unexpected).toEqual([])
})

test('password success clears the inputs and signout bypasses dirty navigation', async ({ page }) => {
  const f = await fixture(page)
  await page.goto('/organizer/settings/account')
  await page.getByRole('button', { name: 'Change password', exact: true }).click()
  await capture(page, 'password-empty-390')
  const secret = randomUUID()
  await page.getByLabel('New password', { exact: true }).fill(secret)
  await page.getByLabel('Confirm new password', { exact: true }).fill(secret)
  await page.getByRole('button', { name: 'Save password', exact: true }).click()
  await expect(page.getByText('Password updated.')).toBeVisible()
  await expect(page.getByLabel('New password', { exact: true })).toHaveCount(0)
  expect(await page.evaluate(() => JSON.stringify(localStorage) + JSON.stringify(sessionStorage))).not.toContain(secret)
  await page.getByRole('button', { name: 'Edit account name' }).click()
  await page.getByRole('textbox', { name: 'Account name', exact: true }).fill('Unsaved account draft')
  await page.getByRole('button', { name: 'Sign out', exact: true }).click()
  await expect(page).toHaveURL(/\/auth\/sign-in$/)
  await expect(page.getByRole('dialog')).toHaveCount(0)
  expect(f.state.signOuts).toBe(1)
})
