begin;
create extension if not exists pgtap with schema extensions;
set local search_path=public,extensions;
select no_plan();
select private.configure_policy_environment('development');
grant select on public.orders,public.order_items,public.tickets to service_role;
\ir ../../supabase/tests/database/helpers/spec09_refund_setup.inc
reset role;
revoke select on public.orders,public.order_items,public.tickets from service_role;
select public.server_configure_waitlist('{"acceptingJoins":true,"observerEnabled":true,"deliveryEnabled":true,"senderEmail":"notify@example.invalid","replyTo":"support@example.invalid","appOrigin":"https://example.invalid","capacityMinute":10000,"capacityDay":10000,"capacityMonth":10000}');
select public.server_acknowledge_waitlist_worker();
update public.ticket_tiers set quantity_total=2 where id='a6300000-0000-4000-8000-000000000001';
select public.server_join_waitlist('a6200000-0000-4000-8000-000000000001','a6300000-0000-4000-8000-000000000001','Buyer','buyer@example.invalid',gen_random_uuid(),repeat('a',64));
create temp table proof(k text primary key,v jsonb);
insert into proof values('claim',public.server_claim_waitlist_delivery());
select is((select v->>'attemptId' from proof where k='claim'),(select id::text from private.waitlist_deliveries),'claim delivery');
select is(public.server_prepare_waitlist_delivery((select (v->>'attemptId')::uuid from proof where k='claim'),(select (v->>'leaseId')::uuid from proof where k='claim'))->>'purpose','confirmation','prepare confirmation facts');
select ok(public.server_save_waitlist_payload((select (v->>'attemptId')::uuid from proof where k='claim'),(select (v->>'leaseId')::uuid from proof where k='claim'),'{"version":1,"keyId":"local","nonce":"AAAAAAAAAAAAAAAA","ciphertext":"AAAAAAAAAAAAAAAAAAAAAA"}',repeat('d',64),(select private.ticket_email_fingerprint(private.waitlist_facts(id)::text) from private.waitlist_enrollments where event_id='a6200000-0000-4000-8000-000000000001' limit 1)),'save encrypted payload and token hash');
select ok(not public.server_save_waitlist_payload((select (v->>'attemptId')::uuid from proof where k='claim'),(select (v->>'leaseId')::uuid from proof where k='claim'),'{"version":1,"keyId":"local","nonce":"AAAAAAAAAAAAAAAA","ciphertext":"AAAAAAAAAAAAAAAAAAAAAA"}',repeat('e',64),(select private.ticket_email_fingerprint(private.waitlist_facts(id)::text) from private.waitlist_enrollments where event_id='a6200000-0000-4000-8000-000000000001' limit 1)),'cannot rotate payload token');
insert into proof values('dispatch',public.server_begin_waitlist_dispatch((select (v->>'attemptId')::uuid from proof where k='claim'),(select (v->>'leaseId')::uuid from proof where k='claim')));
select is((select v->>'idempotencyKey' from proof where k='dispatch'),'waitlist/'||(select id::text from private.waitlist_deliveries),'stable key');
select ok(public.server_finish_waitlist_dispatch((select (v->>'attemptId')::uuid from proof where k='claim'),(select (v->>'leaseId')::uuid from proof where k='claim'),'unknown'),'unknown recorded');
select is((select state from private.waitlist_deliveries),'unknown','unknown is not failure');
select is(public.server_leave_waitlist(repeat('d',64),repeat('b',64))->>'kind','removed','valid leave');
select is(public.server_leave_waitlist(repeat('d',64),repeat('b',64))->>'kind','removed','repeat harmless');
select is(public.server_leave_waitlist(repeat('f',64),repeat('b',64))->>'kind','unavailable','invalid token no information');
select ok(public.server_observe_email('wl-test',(select id from private.waitlist_deliveries),'provider_test','bounced',clock_timestamp()),'late signed-domain evidence accepted');
select is((select state from private.waitlist_deliveries),'accepted','late evidence preserves provider truth after leave');
select is((select observation from private.waitlist_deliveries),'bounced','acceptance is not inbox delivery');
select ok((select waitlist_delivery_id is not null and attempt_id is null and organizer_recipient_id is null from private.ticket_email_recipient_blocks where recipient_hash=private.ticket_email_fingerprint('buyer@example.invalid')),'exactly waitlist suppression provenance');
select throws_ok($$update private.waitlist_deliveries set payload='{"version":1,"keyId":"other","nonce":"AAAAAAAAAAAAAAAA","ciphertext":"AAAAAAAAAAAAAAAAAAAAAA"}'$$,'P0001','Immutable waitlist delivery','payload immutable');
select throws_ok($$update private.waitlist_enrollments set joined_at=clock_timestamp()$$,'P0001','Immutable waitlist enrollment','join time immutable');
select ok(not has_function_privilege('authenticated','public.server_prune_waitlist()','execute'),'retention service-only');
select is(public.server_prune_waitlist(),0,'fresh private data not purged');
select * from finish();
rollback;
