import type { CSSProperties } from 'react'

export const emailStyles: Record<string, CSSProperties> = {
  body: {
    margin: '0',
    padding: '28px 12px',
    backgroundColor: '#12101d',
    color: '#ffffff',
    fontFamily: 'Arial, Helvetica, sans-serif',
  },
  container: {
    maxWidth: '560px',
    margin: '0 auto',
    border: '1px solid #443653',
    borderRadius: '18px',
    overflow: 'hidden',
    backgroundColor: '#1c1728',
  },
  brand: {
    margin: '0',
    padding: '22px 28px',
    backgroundColor: '#6d4aff',
    color: '#ffffff',
    fontSize: '22px',
    fontWeight: '700',
    letterSpacing: '-1px',
  },
  content: { padding: '32px 28px 12px' },
  eyebrow: {
    margin: '0 0 10px',
    color: '#bfa5ff',
    fontSize: '12px',
    fontWeight: '700',
    letterSpacing: '1px',
    textTransform: 'uppercase',
  },
  heading: {
    margin: '0 0 18px',
    color: '#ffffff',
    fontSize: '34px',
    fontWeight: '700',
    letterSpacing: '-1.2px',
    lineHeight: '1.05',
  },
  text: { margin: '0 0 18px', color: '#c6bbd6', fontSize: '16px', lineHeight: '1.6' },
  facts: {
    margin: '0 0 22px',
    borderTop: '1px solid #443653',
    borderBottom: '1px solid #443653',
    padding: '16px 0 0',
  },
  fact: { margin: '0 0 14px', color: '#ffffff', fontSize: '14px', lineHeight: '1.5' },
  button: {
    display: 'block',
    borderRadius: '12px',
    padding: '14px 18px',
    backgroundColor: '#6d4aff',
    color: '#ffffff',
    fontSize: '15px',
    fontWeight: '700',
    textAlign: 'center',
    textDecoration: 'none',
  },
  privacy: { margin: '12px 0 0', color: '#c6bbd6', fontSize: '12px', lineHeight: '1.5' },
  rule: { margin: '24px 0 0', borderColor: '#443653' },
  footer: { margin: '0', padding: '18px 28px 24px', color: '#c6bbd6', fontSize: '12px' },
}
