import type { EventRow } from '../events/event.types'
import type { EventChangeContext } from './eventChanges.schemas'
export const testEvent: EventRow = {
 id: 'event-1', organizer_id: 'organizer-1', status: 'draft', moderation_status: 'clear', content_revision: 1, moderated_revision: null, moderation_version: 0, moderation_updated_at: null, public_history_status: 'never_public', first_publicly_eligible_at: null, public_eligibility_version: 0, publicly_authorized_revision: null, publicly_authorized_action_id: null,
 title: 'Saved title', description: 'Saved description for an evening with local makers.', category: 'community', starts_at: '2027-12-02T02:30:00.000Z', ends_at: '2027-12-02T04:00:00.000Z', timezone: 'America/Los_Angeles', venue_name: 'Saved venue', address_line1: '1 Market St', address_line2: null, city: 'San Francisco', region: 'CA', postal_code: '94105', country_code: 'US', mapbox_feature_id: 'address.saved', latitude: 37.79, longitude: -122.4, location: 'computed geography', admission_type: 'free', capacity: 100, artwork_path: null, animation_preset: 'generic', published_at: null, created_at: '2026-08-24T12:00:00.000Z', updated_at: '2026-08-24T13:00:00.000Z',
}
export function testContext(event: EventRow = testEvent, token = 'baseline-token'): EventChangeContext {
 const requirements: EventChangeContext['requirements'] = {
  minimumAge: '21_plus', alcoholPresent: true, cannabisPresent: false, explicitAdultContent: false, gamblingPresent: false, weaponsPresent: false, highRiskActivity: false, needsAcceptance: true,
  organizerTerms: { policyKind: 'organizer_terms', label: 'Organizer Terms', versionId: 'dev-organizer-terms-v1', stage: 'development_placeholder', publicUrl: '/organizer-terms' },
  eventPolicy: { policyKind: 'event_policy', label: 'Event Policy', versionId: 'dev-event-policy-v1', stage: 'development_placeholder', publicUrl: '/event-policy' },
 }
 return { event_id: event.id, context_token: token, event: { ...event }, requirements, currently_publicly_eligible: false, previous_saved: null, current_saved: { snapshot_id: '11111111-1111-4111-8111-111111111111', snapshot_version: 1, content_revision: 1, captured_at: '2026-09-15T12:00:00Z', facts: { title: event.title, description: event.description, category: event.category, starts_at: event.starts_at, ends_at: event.ends_at, timezone: event.timezone, venue_name: event.venue_name, address_line1: event.address_line1, address_line2: event.address_line2, city: event.city, region: event.region, postal_code: event.postal_code, country_code: event.country_code, mapbox_feature_id: event.mapbox_feature_id, latitude: event.latitude, longitude: event.longitude, admission_type: event.admission_type as 'free' | 'paid', capacity: event.capacity, disclosures: { minimum_age: '21_plus', alcohol_present: true, cannabis_present: false, explicit_adult_content: false, gambling_present: false, weapons_present: false, high_risk_activity: false } } }, previous_publicly_eligible: null, current_publicly_eligible: null, notice_required: false, required_snapshot_id: null, required_fields: [] }
}
