// Development-only catalog, shared by the operator seed and the preview doorway.
// These fixed UUIDs identify fixture records; they are not admission credentials.
export const demoOrganizerId = '8ad057c1-f7b1-4aec-90cb-260908000001'
export const demoOrganizerName = 'Wheretoo Demo Events [DEV]'
export const demoEmail = 'wheretoo-dev-world@example.invalid'
export const demoEvents = [
  { id: '8ad057c1-f7b1-4aec-90cb-260908000011', title: 'After Hours Oakland [DEV]', category: 'music', venue: 'Uptown Listening Room (fictional)', address: '1800 Telegraph Avenue', city: 'Oakland', postal: '94612', latitude: 37.8079, longitude: -122.2695, paid: true, description: 'A fictional evening of soulful house, live percussion and warm Oakland energy. Gather your friends for an intimate listening-room session. Development event only; no real admission or gathering.' },
  { id: '8ad057c1-f7b1-4aec-90cb-260908000012', title: 'Lake Merritt Morning Miles [DEV]', category: 'fitness', venue: 'Lakeside Meet-up (fictional)', address: '568 Bellevue Avenue', city: 'Oakland', postal: '94610', latitude: 37.8078, longitude: -122.2583, paid: false, description: 'An easy-paced social run beside the lake, followed by stretching and conversation. All paces welcome. Fictional development event; no real gathering.' },
  { id: '8ad057c1-f7b1-4aec-90cb-260908000013', title: 'Golden Hour Rooftop [DEV]', category: 'community', venue: 'Skyline Terrace (fictional)', address: '1500 Broadway', city: 'Oakland', postal: '94612', latitude: 37.8053, longitude: -122.271, paid: false, description: 'Watch the skyline glow over an afternoon of acoustic sounds and neighborhood conversation. Fictional development event; no real gathering.' },
  { id: '8ad057c1-f7b1-4aec-90cb-260908000014', title: 'Color & Conversation [DEV]', category: 'art_culture', venue: 'Mission Color Studio (fictional)', address: '2301 Mission Street', city: 'San Francisco', postal: '94110', latitude: 37.7608, longitude: -122.4194, paid: false, description: 'A relaxed painting workshop with tea, sparkling refreshments and plenty of color. Materials provided in this imaginary event. Development sample only.' },
  { id: '8ad057c1-f7b1-4aec-90cb-260908000015', title: 'Sunday Food Pop-up [DEV]', category: 'food_drink', venue: 'Waterfront Courtyard (fictional)', address: '1 Ferry Building', city: 'San Francisco', postal: '94111', latitude: 37.7955, longitude: -122.3937, paid: false, description: 'An imaginary courtyard of seasonal bites, local makers and waterfront conversation. Explore a sample Bay Area food gathering. Development event only.' },
  { id: '8ad057c1-f7b1-4aec-90cb-260908000016', title: 'Neighborhood Day Party [DEV]', category: 'music', venue: 'West Oakland Yard (fictional)', address: '1700 7th Street', city: 'Oakland', postal: '94607', latitude: 37.8047, longitude: -122.2965, paid: false, description: 'Sunshine, mellow DJ selections and room to dance with your neighbors. This is a fictional development record, not an actual scheduled gathering.' },
  { id: '8ad057c1-f7b1-4aec-90cb-260908000017', title: 'Sunday Reset & Stretch [DEV]', category: 'fitness', venue: 'Garden Studio (fictional)', address: '1199 9th Avenue', city: 'San Francisco', postal: '94122', latitude: 37.765, longitude: -122.4662, paid: false, description: 'A gentle morning of mindful movement, stretching and quiet reflection. Bring an imaginary mat. Fictional development event; no real gathering.' },
] as const
export const demoTiers = [
  { id: '8ad057c1-f7b1-4aec-90cb-260908000021', name: 'General Admission', description: 'Entry to the full evening', unit_amount_minor: 2000, quantity_total: 500, sort_order: 1 },
  { id: '8ad057c1-f7b1-4aec-90cb-260908000022', name: 'VIP', description: 'Entry plus the fictional balcony lounge', unit_amount_minor: 4500, quantity_total: 100, sort_order: 2 },
] as const
