import { BrowserRouter, Link, Route, Routes, useParams } from 'react-router-dom'
import { TicketSelectionPreviewPage } from '../features/tickets/TicketSelectionPreviewPage'
import { EventPolicyPage } from '../features/moderation/EventPolicyPage'
import { OrganizerTermsPage } from '../features/moderation/OrganizerTermsPage'
import { previewSections } from './catalog'
import screens from './screens.json'
import './preview.css'

function PreviewHub() {
  return (
    <main className="preview-hub">
      <header>
        <p className="organizer-eyebrow">Development preview only</p>
        <h1>Wheretoo screen hub</h1>
        <p>One place to inspect the current frontend and track the buyer journey.</p>
        <p>Local sample data. Screen captures are read-only: forms, links, publishing and payments are inactive.</p>
      </header>
      {previewSections.map((section, index) => (
        <section aria-labelledby={`preview-section-${index}`} key={section.title}>
          <h2 id={`preview-section-${index}`}>{section.title}</h2>
          <ul>
            {section.screens.map((screen) => (
              <li key={screen.label}>
                <div>
                  {screen.slug ? <Link to={`/preview/${screen.slug}`}>{screen.label}<span aria-hidden="true"> ↗</span></Link> : <strong>{screen.label}</strong>}
                  {screen.route ? <code>{screen.route}</code> : null}
                  {screen.note ? <small>{screen.note}</small> : null}
                </div>
                <span className="preview-hub__status">{screen.status ?? 'Open preview'}</span>
              </li>
            ))}
          </ul>
        </section>
      ))}
    </main>
  )
}

function PreviewScreen() {
  const { slug = '' } = useParams()
  const screen = previewSections.flatMap((section) => section.screens).find((entry) => entry.slug === slug)
  const html = Object.hasOwn(screens, slug) ? screens[slug as keyof typeof screens] : undefined
  return (
    <>
      <header className="preview-toolbar">
        <Link to="/preview">← Screen hub</Link>
        <p><strong>Development preview only</strong> · {screen?.label ?? 'Screen not found'}</p>
        <span>Local sample data · No live transactions</span>
      </header>
      {slug === 'ticket-selection' ? <TicketSelectionPreviewPage />
        : slug === 'organizer-terms' ? <OrganizerTermsPage />
          : slug === 'event-policy' ? <EventPolicyPage />
            : html ? (
              <>
                <p className="preview-caption">Read-only capture of the real screen. Use “Screen hub” to navigate.</p>
                {/* Generated by the fixture renderer, never from user input or an API.
                    No React hydration means no production handlers or effects can run. */}
                <div inert dangerouslySetInnerHTML={{ __html: html }} />
              </>
            ) : <main className="preview-hub"><h1>Screen not found</h1><p>Choose an available screen from the hub.</p></main>}
    </>
  )
}

export function PreviewApp() {
  return (
    <BrowserRouter>
      <Routes>
        <Route path="/preview" element={<PreviewHub />} />
        <Route path="/preview/:slug" element={<PreviewScreen />} />
        <Route path="*" element={<PreviewScreen />} />
      </Routes>
    </BrowserRouter>
  )
}
